"""One run as a single self-contained HTML page, for someone without Gauntlet.

The page is built from the run's row, its notes and the files in its
directory, and reads nothing else, so an imported run reports the same as the
one that produced it. Every file is optional: a section whose file is missing
or unreadable is left out rather than failing the report.

Nothing is fetched when the page is opened. Charts are inline SVG and the
styles are in the page, so it can be mailed, archived or printed to PDF as it
is.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from html import escape
from pathlib import Path
from typing import Any

import yaml

from gauntlet import __version__
from gauntlet.storage import NoteRow, RunRow
from gauntlet.supervisor.readers import flatten

# A chart draws at most this many points; a longer series is thinned evenly.
# Enough to show the shape of a run, few enough that a long soak with many
# series still makes a page a browser opens quickly.
_MAX_CHART_POINTS = 400

# Failed iterations listed by reason. A run failing every iteration of a long
# soak would otherwise list thousands.
_MAX_FAILURES = 50

_CHART_WIDTH = 600
_CHART_HEIGHT = 120


def report_name(run_id: str) -> str:
    """The file name a run's report is offered under."""
    return f"{run_id}.report.html"


def render_report(row: RunRow, notes: list[NoteRow], campaign: str | None) -> str:
    """The whole report for one run, as an HTML document."""
    run_dir = Path(row.run_dir)
    sections = [
        _run_section(row, campaign),
        _verdict_section(_read_json(run_dir / "verdict.json")),
        _metrics_section(_read_records(run_dir / "metrics.jsonl")),
        _instruments_section(_read_json(run_dir / "instruments.json")),
        _notes_section(notes),
        _profile_section(run_dir),
        _provenance_section(_read_json(run_dir / "manifest.json")),
        _artifacts_section(run_dir),
    ]
    generated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%SZ")
    title = f"{row.suite} · {row.run_id}"
    return "\n".join(
        [
            "<!doctype html>",
            '<html lang="en">',
            "<head>",
            '<meta charset="utf-8">',
            '<meta name="viewport" content="width=device-width, initial-scale=1">',
            f"<title>{escape(title)}</title>",
            f"<style>{_STYLE}</style>",
            "</head>",
            "<body>",
            "<header>",
            f"<h1>{escape(row.suite)}</h1>",
            f'<p class="run-id">{escape(row.run_id)}</p>',
            f'<p class="status status-{escape(row.status)}">{escape(row.status.upper())}</p>',
            "</header>",
            *[section for section in sections if section],
            f"<footer>Generated by Gauntlet {escape(__version__)} at {generated}</footer>",
            "</body>",
            "</html>",
            "",
        ]
    )


def _run_section(row: RunRow, campaign: str | None) -> str:
    rows = [
        ("Status", row.status),
        ("Verdict", row.verdict),
        ("Failure reason", row.fail_reason),
        ("Profile", row.profile),
        ("Campaign", campaign),
        ("Unit", row.unit_serial),
        ("Target", row.target),
        ("Started", row.started_at),
        ("Ended", row.ended_at),
        ("Duration", _duration(row.duration_s)),
        ("Operator", row.operator),
        ("Location", row.location),
        ("Session", row.session),
    ]
    return _section("Run", _definitions(rows))


def _verdict_section(verdict: Any) -> str:
    if not isinstance(verdict, dict):
        return ""
    rows = [
        ("Passed", _yes_no(verdict.get("passed"))),
        ("Reason", verdict.get("reason")),
        ("Iterations", verdict.get("total_iterations")),
        ("Successes", verdict.get("successes")),
        ("Failures", verdict.get("failures")),
        ("Stopped early", "yes" if verdict.get("stopped_early") else None),
        ("Aborted", (verdict.get("abort_reason") or "yes") if verdict.get("aborted") else None),
    ]
    parts = [_definitions(rows)]

    results = [result for result in verdict.get("results") or [] if isinstance(result, dict)]
    if results:
        body = [
            [str(result.get("label") or result.get("key", "")), _with_unit(result.get("value"), result.get("unit"))]
            for result in results
        ]
        parts += ["<h3>Results</h3>", _table(["Result", "Value"], body)]

    tests = [test for test in verdict.get("tests") or [] if isinstance(test, dict)]
    if tests:
        body = [
            [
                str(test.get("name", "")),
                str(test.get("outcome", "")),
                _duration(test.get("duration_s")) or "",
                str(test.get("message", "")),
            ]
            for test in tests
        ]
        parts += ["<h3>Tests</h3>", _table(["Test", "Outcome", "Duration", "Message"], body)]
    return _section("Verdict", "\n".join(parts))


def _metrics_section(records: list[dict[str, Any]]) -> str:
    if not records:
        return ""
    iterations = [record for record in records if record.get("kind", "iteration") == "iteration"]
    failed = [record for record in iterations if record.get("success") is False]
    anomalies = [record for record in records if record.get("kind") == "anomaly"]
    counts = [
        ("Iterations", len(iterations)),
        ("Failed iterations", len(failed)),
        ("Anomalies", len(anomalies)),
    ]
    parts = [_definitions(counts)]

    series = _series(records)
    if series:
        body = []
        charts = []
        for name, points in series.items():
            values = [value for _, value in points]
            body.append(
                [
                    name,
                    str(len(values)),
                    _number(min(values)),
                    _number(max(values)),
                    _number(sum(values) / len(values)),
                    _number(values[-1]),
                ]
            )
            # A series that never changed says all it has to in the table.
            if min(values) != max(values):
                charts.append(f"<figure><figcaption>{escape(name)}</figcaption>{_chart(points)}</figure>")
        parts += ["<h3>Series</h3>", _table(["Metric", "Samples", "Min", "Max", "Mean", "Last"], body)]
        parts += charts

    if failed:
        body = [[str(record.get("iteration", "")), str(record.get("reason", ""))] for record in failed[:_MAX_FAILURES]]
        parts += ["<h3>Failed iterations</h3>", _table(["Iteration", "Reason"], body)]
        if len(failed) > _MAX_FAILURES:
            parts.append(f'<p class="muted">First {_MAX_FAILURES} of {len(failed)} shown.</p>')
    return _section("Metrics", "\n".join(parts))


def _series(records: list[dict[str, Any]]) -> dict[str, list[tuple[float, float]]]:
    """Every numeric metric, as (elapsed seconds, value) pairs in record order.

    A record without ``elapsed_run_s`` is placed by its position in the file,
    so a suite that never writes it still gets a chart.
    """
    series: dict[str, list[tuple[float, float]]] = {}
    for position, record in enumerate(records):
        if record.get("kind", "iteration") not in ("iteration", "live"):
            continue
        elapsed = record.get("elapsed_run_s")
        x = float(elapsed) if isinstance(elapsed, (int, float)) else float(position)
        for name, value in flatten(record.get("metrics") or {}):
            if isinstance(value, bool):
                continue
            series.setdefault(name, []).append((x, float(value)))
    return dict(sorted(series.items()))


def _chart(points: list[tuple[float, float]]) -> str:
    """A line chart of one series, as inline SVG scaled to fit its box."""
    step = max(1, len(points) // _MAX_CHART_POINTS)
    shown = points[::step]
    xs = [x for x, _ in shown]
    ys = [y for _, y in shown]
    x_low, x_high = min(xs), max(xs)
    y_low, y_high = min(ys), max(ys)
    x_span = (x_high - x_low) or 1.0
    y_span = (y_high - y_low) or 1.0
    coordinates = " ".join(
        f"{(x - x_low) / x_span * _CHART_WIDTH:.1f},{_CHART_HEIGHT - (y - y_low) / y_span * _CHART_HEIGHT:.1f}"
        for x, y in shown
    )
    return (
        f'<svg viewBox="0 0 {_CHART_WIDTH} {_CHART_HEIGHT}" preserveAspectRatio="none" role="img">'
        f'<polyline points="{coordinates}" /></svg>'
        f'<div class="axis"><span>{_number(y_low)} &ndash; {_number(y_high)}</span>'
        f"<span>{_duration(x_low)} &ndash; {_duration(x_high)}</span></div>"
    )


def _instruments_section(summary: Any) -> str:
    if not isinstance(summary, dict):
        return ""
    parts = []
    for instrument in summary.get("instruments") or []:
        if not isinstance(instrument, dict):
            continue
        readings = [reading for reading in instrument.get("readings") or [] if isinstance(reading, dict)]
        if not readings:
            continue
        heading = str(instrument.get("name", ""))
        if instrument.get("description"):
            heading += f" — {instrument['description']}"
        body = [
            [
                str(reading.get("label") or reading.get("key", "")),
                str(reading.get("unit", "")),
                _number(reading.get("min")),
                _number(reading.get("max")),
                _number(reading.get("mean")),
                _number(reading.get("last")),
            ]
            for reading in readings
        ]
        headings = ["Reading", "Unit", "Min", "Max", "Mean", "Last"]
        # A multi-channel instrument labels each channel's readings alike, so
        # only the group tells them apart.
        if any(reading.get("group") for reading in readings):
            headings.insert(0, "Group")
            for row, reading in zip(body, readings, strict=True):
                row.insert(0, str(reading.get("group") or ""))
        parts += [f"<h3>{escape(heading)}</h3>", _table(headings, body)]
    return _section("Instruments", "\n".join(parts)) if parts else ""


def _notes_section(notes: list[NoteRow]) -> str:
    if not notes:
        return ""
    parts = []
    for note in sorted(notes, key=lambda note: note.id):
        heading = " · ".join(filter(None, [note.created_at, note.author, note.location, note.session]))
        parts.append(
            f'<div class="note"><p class="muted">{escape(heading)}</p><p class="note-body">{escape(note.body)}</p></div>'
        )
    return _section("Notes", "\n".join(parts))


def _profile_section(run_dir: Path) -> str:
    """The profile as the run resolved it, one row per setting.

    ``profile.yaml`` is read first because the suite rewrites it with every
    default filled in; the copy in ``manifest.json`` stands in when it is
    missing or does not parse.
    """
    profile = _read_yaml(run_dir / "profile.yaml")
    if not isinstance(profile, dict):
        manifest = _read_json(run_dir / "manifest.json")
        profile = manifest.get("profile") if isinstance(manifest, dict) else None
    if not isinstance(profile, dict) or not profile:
        return ""
    return _section("Profile", _table(["Setting", "Value"], _settings(profile)))


def _settings(value: Any, prefix: str = "") -> list[list[str]]:
    """Nested settings as dotted names and printable values.

    A list of plain values is one row; a list holding mappings gets a row per
    field of each item, numbered, so a list of devices reads as one block each.
    """
    if isinstance(value, dict):
        if not value and prefix:
            return [[prefix, "-"]]
        rows = []
        for key, child in value.items():
            rows += _settings(child, f"{prefix}.{key}" if prefix else str(key))
        return rows
    if isinstance(value, list) and any(isinstance(item, (dict, list)) for item in value):
        rows = []
        for position, item in enumerate(value):
            rows += _settings(item, f"{prefix}[{position}]")
        return rows
    if isinstance(value, list):
        return [[prefix, ", ".join(_setting(item) for item in value) or "-"]]
    return [[prefix, _setting(value)]]


def _setting(value: Any) -> str:
    if value is None or value == "":
        return "-"
    if isinstance(value, bool):
        return "yes" if value else "no"
    return str(value)


def _provenance_section(manifest: Any) -> str:
    if not isinstance(manifest, dict):
        return ""
    command = manifest.get("command_line")
    repo = manifest.get("repo_sha")
    if repo and manifest.get("repo_branch"):
        repo = f"{repo} ({manifest['repo_branch']})"
    if repo and manifest.get("repo_dirty"):
        repo = f"{repo}, dirty"
    rows = [
        ("Host", manifest.get("hostname")),
        ("Operator", manifest.get("operator")),
        ("Platform", manifest.get("platform")),
        ("Python", manifest.get("python_version")),
        ("Gauntlet", manifest.get("gauntlet_version")),
        ("Gauntlet commit", manifest.get("gauntlet_git_sha")),
        ("Suite commit", repo),
        ("Command", " ".join(str(part) for part in command) if isinstance(command, list) else None),
        ("Profile file", manifest.get("profile_path")),
    ]
    parts = [_definitions(rows)]
    versions = manifest.get("versions")
    if isinstance(versions, dict) and versions:
        body = [[str(name), str(version)] for name, version in sorted(versions.items())]
        parts += ["<h3>Versions</h3>", _table(["Component", "Version"], body)]
    hardware = manifest.get("hardware")
    if isinstance(hardware, dict) and hardware:
        body = [
            [str(device), str(field), str(value)]
            for device, fields in sorted(hardware.items())
            if isinstance(fields, dict)
            for field, value in sorted(fields.items())
        ]
        parts += ["<h3>Hardware</h3>", _table(["Device", "Field", "Value"], body)]
    return _section("Provenance", "\n".join(parts))


def _artifacts_section(run_dir: Path) -> str:
    if not run_dir.is_dir():
        return ""
    body = [
        [str(path.relative_to(run_dir)), _size(path.stat().st_size)]
        for path in sorted(run_dir.rglob("*"))
        if path.is_file()
    ]
    return _section("Artifacts", _table(["File", "Size"], body)) if body else ""


def _section(title: str, body: str) -> str:
    return f"<section><h2>{escape(title)}</h2>\n{body}\n</section>"


def _definitions(rows: list[tuple[str, Any]]) -> str:
    """A two-column table of the rows that have a value."""
    body = "".join(
        f"<tr><th>{escape(label)}</th><td>{escape(str(value))}</td></tr>"
        for label, value in rows
        if value is not None and value != ""
    )
    return f'<table class="definitions">{body}</table>'


def _table(headings: list[str], rows: list[list[str]]) -> str:
    head = "".join(f"<th>{escape(heading)}</th>" for heading in headings)
    body = "".join("<tr>" + "".join(f"<td>{escape(cell)}</td>" for cell in row) + "</tr>" for row in rows)
    return f"<table><thead><tr>{head}</tr></thead><tbody>{body}</tbody></table>"


def _read_text(path: Path) -> str | None:
    try:
        return path.read_text(errors="replace")
    except OSError:
        return None


def _read_json(path: Path) -> Any:
    text = _read_text(path)
    if text is None:
        return None
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        return None


def _read_yaml(path: Path) -> Any:
    text = _read_text(path)
    if text is None:
        return None
    try:
        return yaml.safe_load(text)
    except yaml.YAMLError:
        return None


def _read_records(path: Path) -> list[dict[str, Any]]:
    """The records of a ``metrics.jsonl``, skipping any line that is not one."""
    text = _read_text(path)
    if text is None:
        return []
    records = []
    for line in text.splitlines():
        try:
            record = json.loads(line)
        except json.JSONDecodeError:
            continue
        if isinstance(record, dict):
            records.append(record)
    return records


def _number(value: Any) -> str:
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        return ""
    return f"{value:.6g}"


def _with_unit(value: Any, unit: Any) -> str:
    text = _number(value) if isinstance(value, (int, float)) else str(value)
    return f"{text} {unit}" if unit else text


def _yes_no(value: Any) -> str | None:
    if value is None:
        return None
    return "yes" if value else "no"


def _duration(seconds: Any) -> str | None:
    if not isinstance(seconds, (int, float)):
        return None
    minutes, remainder = divmod(round(seconds), 60)
    hours, minutes = divmod(minutes, 60)
    if hours:
        return f"{hours}h {minutes:02d}m {remainder:02d}s"
    if minutes:
        return f"{minutes}m {remainder:02d}s"
    return f"{seconds:.1f}s"


def _size(size: int) -> str:
    if size < 1024:
        return f"{size} B"
    scaled = size / 1024
    for unit in ("KiB", "MiB"):
        if scaled < 1024:
            return f"{scaled:.1f} {unit}"
        scaled /= 1024
    return f"{scaled:.1f} GiB"


# Light and print-friendly, unlike the dark UI: this page is read on paper and
# in mail clients as often as on a bench screen.
_STYLE = """
body { font: 14px/1.45 system-ui, sans-serif; color: #1d1f23; background: #fff;
  max-width: 960px; margin: 0 auto; padding: 24px 16px; }
h1 { margin: 0; font-size: 24px; }
h2 { font-size: 17px; border-bottom: 1px solid #d5d8de; padding-bottom: 4px; margin-top: 32px; }
h3 { font-size: 14px; margin: 20px 0 6px; }
.run-id { margin: 2px 0 8px; font-family: ui-monospace, monospace; color: #5b616b; }
.status { display: inline-block; margin: 0; padding: 2px 10px; font-weight: 600; background: #e9ebef; }
.status-passed { background: #d8f0dc; color: #1c6b2a; }
.status-failed, .status-error { background: #f8dcdc; color: #9b1c1c; }
.status-aborted, .status-interrupted { background: #fbeccc; color: #7a5200; }
table { border-collapse: collapse; width: 100%; margin: 6px 0; font-variant-numeric: tabular-nums; }
th, td { text-align: left; padding: 3px 8px; border-bottom: 1px solid #eceef1; vertical-align: top; }
thead th { border-bottom: 1px solid #b9bec7; }
.definitions th { width: 180px; font-weight: 500; color: #5b616b; }
figure { margin: 14px 0; break-inside: avoid; }
figcaption { font-family: ui-monospace, monospace; font-size: 12px; margin-bottom: 2px; }
svg { display: block; width: 100%; height: 120px; background: #f8f9fa; }
polyline { fill: none; stroke: #2463c8; stroke-width: 1.5; vector-effect: non-scaling-stroke; }
.axis { display: flex; justify-content: space-between; font-size: 11px; color: #5b616b; }
.muted { color: #5b616b; font-size: 12px; margin: 0; }
.note { margin: 10px 0; }
.note-body { white-space: pre-wrap; margin: 2px 0 0; }
footer { margin-top: 40px; font-size: 12px; color: #8a9099; }
section { break-inside: auto; }
"""
